### ISSUE TITLE
Discord made me racist 😣😣😣

### ISSUE THREAD

**Issue by xAqaze** [namooTH/deltafall-bot#1]
Last time when I was 9 years old, my 29 years old roblox friend told me to download an app called discord.
So after using discord for 3 years, I found multiple racist servers that I joined. They all send nazi and geroge floyd.
They say n word and shit and now I say the n word too. I think saying n word is so funny. I say heil hitler too 😂😂😂
Everytime I post gore, me and the boys can’t stop laughing. We jack off to fortnite sex too.
I am now racist and a nazi 😂😂😂😂😂😂😂😂😂

**Comment by namooTH** [comment]
real
